before_script:
  - apt-get update && apt-get install -y openssh-client python-catkin-tools build-essential
  - source `find /opt/ros -name setup.bash | sort | head -1` && echo $ROS_DISTRO
  - mkdir src && mv `find -maxdepth 1 -not -name . -not -name src` src/
  - git init src/astuff_sensor_msgs && cd src/astuff_sensor_msgs && git remote add origin https://github.com/astuff/astuff_sensor_msgs && git config core.sparsecheckout true && echo "pacmod_msgs/*" >> .git/info/sparse-checkout && git pull --depth=1 origin master && cd ../..
  - rosdep update
  - rosdep install --from-paths src --ignore-src -y
  - catkin init

indigo:
  image: "ros:indigo-ros-core"
  script:
    - catkin build -j2
    - catkin run_tests -j2

kinetic:
  image: "ros:kinetic-ros-core"
  script:
    - catkin build -j2
    - catkin run_tests -j2

lunar:
  image: "ros:lunar-ros-core"
  script:
    - catkin build -j2
    - catkin run_tests -j2

melodic:
  image: "ros:melodic-ros-core"
  script:
    - catkin build -j2
    - catkin run_tests -j2
